language: rust
rust: nightly

before_install:
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libnanomsg-dev libportaudio-dev libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev opencl-headers fglrx

script:
  - ( cd common && cargo test --verbose )
  - ( cd client && cargo test --verbose )
  - ( cd server && cargo test --verbose )
