[package]

name = "playform"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Elijah Andrews <elijahcandrews@gmail.com>",
  ]

[[bin]]

name = "playform"
path = "./src/playform.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.sdl2_game_window]
# only until PistonDevelopers/piston#508 and  is merged.
git = "https://github.com/bfops/sdl2_game_window"

[dependencies.piston]
# only until PistonDevelopers/piston#508 is merged.
git = "https://github.com/cgaebel/piston"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
