[package]

name = "playform"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Elijah Andrews <elijahcandrews@gmail.com>",
  ]

[[bin]]

name = "playform"
path = "./src/playform.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window"

[dependencies.current]
git = "https://github.com/PistonDevelopers/current"

[dependencies.event]
git = "https://github.com/PistonDevelopers/event"

[dependencies.input]
git = "https://github.com/PistonDevelopers/input"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.png]
git = "https://github.com/sebcrozet/rust-png"

[dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"

[dependencies.ncollide]
features = ["3df32"]
git = "https://github.com/sebcrozet/ncollide"

[dependencies.noise-rs]
git = "https://github.com/bjz/noise-rs"

[dependencies.glw]
git = "https://github.com/bfops/glw"
