[package]

name = "playform"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
  ]

[[bin]]

name = "playform"
path = "./src/main.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.sdl2_game_window]
# until https://github.com/PistonDevelopers/rust-sdl2/pull/5 is resolved.
git = "https://github.com/RobotGymnast/sdl2_game_window"

[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"

[dependencies.cgmath]
# until https://github.com/bjz/cgmath-rs/pull/101 is resolved.
git = "https://github.com/RobotGymnast/cgmath-rs"
