[package]

name = "playform"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Elijah Andrews <elijahcandrews@gmail.com>",
  ]

[[bin]]

name = "playform"
path = "./src/playform.rs"

[dependencies]
time = "*"
log = "*"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"

[dependencies.yaglw]
git = "https://github.com/bfops/yaglw"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide]
features = ["3df32"]
git = "https://github.com/sebcrozet/ncollide"

[dependencies.noise]
git = "https://github.com/bjz/noise-rs"
