[package]

name = "playform"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Elijah Andrews <elijahcandrews@gmail.com>",
  ]

# The development profile, used for `cargo build`
[profile.dev]
opt-level = 3
debug = true
rpath = false
lto = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false

[[bin]]
name = "playform"
path = "./src/playform.rs"

[dependencies]
time = "*"
log = "*"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.sdl2]
git = "https://github.com/FreeFull/rust-sdl2"

[dependencies.yaglw]
git = "https://github.com/bfops/yaglw"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide]
git = "https://github.com/sebcrozet/ncollide"

[dependencies.noise]
git = "https://github.com/bjz/noise-rs"
