[package]

name = "playform"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Elijah Andrews <elijahcandrews@gmail.com>",
  ]

[[bin]]

name = "playform"
path = "./src/playform.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.sdl2_game_window]
git = "https://github.com/bfops/sdl2_game_window"

[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide3df32]
git = "https://github.com/sebcrozet/ncollide"
