[package]
name = "glw"
version = "0.0.0"
authors = []

[lib]
name = "glw"
path = "glw.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"
