[package]

name = "playform-server"
version = "0.0.0"
authors = []

[[bin]]
name = "server"
path = "./src/mod.rs"

[dependencies]
env_logger= "*"
log = "*"
num = "*"
rand = "*"
time = "*"

[dependencies.playform-common]
path = "../common"
version = "*"

[dependencies.terrain]
path = "terrain"
version = "*"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.stopwatch]
git = "https://github.com/bfops/stopwatch-rs"
