[package]

name = "playform-server"
version = "0.0.0"
authors = [
    "Ben Foppa <benjamin.foppa@gmail.com>",
    "Clark Gaebel <cg.wowus.cg@gmail.com>",
    "Elijah Andrews <elijahcandrews@gmail.com>",
  ]

# The development profile, used for `cargo build`
[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = false

[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false

[[bin]]
name = "server"
path = "./src/mod.rs"

[dependencies]
env_logger= "*"
log = "*"
num = "*"
rand = "*"
time = "*"

[dependencies.playform-common]
path = "../common"
version = "*"

[dependencies.bit-svo]
git = "https://github.com/bfops/bit-svo"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[dependencies.noise]
git = "https://github.com/bjz/noise-rs"
